# 00. Pytorch Fundamentals #

Resorce notebook: 
https://www.learnpytorch.io/

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.12.1


## Introduction to tensors ##

### Creating tensors ###

PyTorch tensors are created using `torch.tensor()` = https://docs.pytorch.org/docs/2.13/tensors.html


In [7]:
# scalar(标量)
scalar = torch.tensor(7)
scalar

tensor(7)

In [8]:
scalar.ndim

0

In [ ]:
# Get tensor back as Python int
scalar.item()

7

In [10]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [13]:
vector.ndim

1

In [14]:
vector.shape

torch.Size([2])

In [15]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX


tensor([[ 7,  8],
        [ 9, 10]])

In [16]:
MATRIX.ndim

2

In [17]:
MATRIX.shape

torch.Size([2, 2])

In [18]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                       [4,5,6],
                       [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [19]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random Tensors ###

Why Random Tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers -> ...`