# 00. Pytorch Fundamentals #

Resorce notebook: 
https://www.learnpytorch.io/

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.12.1


## Introduction to tensors ##

### Creating tensors ###

PyTorch tensors are created using `torch.tensor()` = https://docs.pytorch.org/docs/2.13/tensors.html


In [3]:
# scalar(标量)
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# Get tensor back as Python int
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX


tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                       [4,5,6],
                       [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random Tensors ###

Why Random Tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers -> ...`

Torch random tensors - https://docs.pytorch.org/docs/2.13/generated/torch.rand.html#torch-rand

In [15]:
# Create a random tensor of shape (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.4616, 0.1561, 0.9536, 0.1107],
        [0.2909, 0.1925, 0.1158, 0.1750],
        [0.5939, 0.3181, 0.7792, 0.6143]])

In [16]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (244,244,3)) #height, width, channels(Red, Green, Blue)
random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([244, 244, 3]), 3)

### Zeros and Ones ###


In [17]:
# Create a tensor of all zeros
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [18]:
# Create a tensor of all ones
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [19]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like ###

In [20]:
# Use torch.arange()
one_to_ten = torch.arange(start = 1, end = 10, step = 1)
one_to_ten

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
# Creating tensors like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes ###

**Note:** Tensor datatypes is one of the 3 big errors you'll run inro with Pytorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [22]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                                dtype = torch.float32, # what datatype ia the tensor
                                device = None, # what device is your tensor on
                                requires_grad = False) # whether or not to track gradients with this tensors operations


In [23]:
float_32_tensor

tensor([3., 6., 9.])

In [24]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor


tensor([3., 6., 9.], dtype=torch.float16)

In [25]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [26]:
int_32_tensor = torch.tensor([3, 6, 9],dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

### Getting information from tensors ###

1. to get datatype of tensor, can use `.dtype` attribute
2. to get shape of tensor, can use `.shape` attribute
3. to get device of tensor, can use `.device` attribute


In [27]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.9132, 0.0147, 0.7803, 0.4446],
        [0.6578, 0.3671, 0.5457, 0.3876],
        [0.9144, 0.8578, 0.6714, 0.4793]])

In [28]:
# Find out details about some_tensor
print(some_tensor)
print(f"Datatype of some_tensor: {some_tensor.dtype}")
print(f"Shape of some_tensor: {some_tensor.shape}")
print(f"Device of some_tensor: {some_tensor.device}")


tensor([[0.9132, 0.0147, 0.7803, 0.4446],
        [0.6578, 0.3671, 0.5457, 0.3876],
        [0.9144, 0.8578, 0.6714, 0.4793]])
Datatype of some_tensor: torch.float32
Shape of some_tensor: torch.Size([3, 4])
Device of some_tensor: cpu


### Manipulating Tensors (tensor operations) ###

Tensor operations include:
* Addition
* Subtraction
* Multiplication(element-wise)
* Division
* Matrix Multiplication


In [29]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [30]:
# Multiply tensor by 10
tensor * 10
tensor

tensor([1, 2, 3])

In [31]:
# Substract 10
tensor - 10
tensor

tensor([1, 2, 3])

In [32]:
# try out pytorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix multiplication ###

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication(dort product)

There are two main rules that performing matrix mutiplication needs to satisfy:
1. The **inner dimensions** must match
2. The resulting matrix has the shape of the **outer dimensions**


In [33]:
# Element-wise multiplication
print(tensor, "*" , tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [34]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

### One of the most common error in deep learning: shape errors ###

In [36]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])
# torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [37]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [39]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [43]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape}(same shape as above), tensor_B = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2])(same shape as above), tensor_B = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum, etx(tensor aggregation)


In [44]:
# Create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Find the min
torch.min(x), x.min()

(tensor(90), tensor(90))

In [ ]:
# Find the max
torch.max(x), x.max()

In [ ]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [49]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max

In [50]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position of target tensor where the minimum value oxxurs
x.argmin()

tensor(0)

In [51]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Rshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeezing - removes all `1` dimensions from a tensor
* Unqueezing - adds a `1` dimension to a target tensor
* Permute - Return a view of the input with dimentions permuted(swapped) in a certain way

In [57]:
# Let's create a tensor
x = torch.arange(1, 10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [58]:
# Addan extra dimention
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [59]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x(because a view of a tensor shares the same memory as the original tensor)
z[:, 0] = 5
z, x

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [65]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim = 0)
x_stacked, x_stacked.shape

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9],
         [5, 2, 3, 4, 5, 6, 7, 8, 9],
         [5, 2, 3, 4, 5, 6, 7, 8, 9],
         [5, 2, 3, 4, 5, 6, 7, 8, 9]]),
 torch.Size([4, 9]))

In [70]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])
New shape: torch.Size([9])


In [74]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extrs dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim = 1)
print(f"\nNew target: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])
Previous shape: torch.Size([9])

New target: tensor([[5],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])
New shape: torch.Size([9, 1])


In [76]:
# torch.permute - rearranges the dimensions of a target tensor in a specific order
x_original = torch.rand(size = (224, 224, 3))

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2,0,1)

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [77]:
x_original[0,0,0] = 728218
x_original[0,0,0], x_permuted[0,0,0]

(tensor(728218.), tensor(728218.))

## Indexing (selecting data from tensors)

Indexing with Pytorch is similar to indexing with NumPy.

In [78]:
# Create a tensor
x = torch.arange(1, 10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [79]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Let's omdex on the middle bracket (dim = 1)
x[0][0]

tensor([1, 2, 3])

In [86]:
# Let's index on the most inner bracket (last dimension)
x[0][0][0]

tensor(1)

In [ ]:
# You can also use ":" to select "all" of a target dimension
x[:, 0]


tensor([[1, 2, 3]])

In [88]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
# Get all values of thee 0 dimension but only the 1 index values of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [91]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [92]:
# index on x to return 9
print(x[0][2][2])

# index on x to return 3,6,9
print(x[:,:,2])


tensor(9)
tensor([[3, 6, 9]])


## Pytorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library.

And because of this, Pytorch has functionality to inyeract with it.

* Data in NumPy, want in Pytorch tensor -> `torch.from_numpy(ndarray)`
* Pytorch tensor -> NumPy -> `tensor.numpy()`

In [94]:
# NumPy array to tensor
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [95]:
# Change the value of array, what will this do to tensor?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [96]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [97]:
# Change the tensor, what happens to numpy_tensor?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take the random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...`

To reduce the randomness in neural networks and Pytorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness.

In [98]:
# Create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.7263, 0.5551, 0.8399, 0.5633],
        [0.2371, 0.6846, 0.0444, 0.9012],
        [0.4813, 0.5776, 0.7986, 0.2475]])
tensor([[0.5974, 0.2922, 0.6083, 0.5053],
        [0.2442, 0.8974, 0.7859, 0.4207],
        [0.3722, 0.3033, 0.5013, 0.9082]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [100]:
# Let's make some random but reproducible tensors

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Extra resources for reproducibility
 * https://docs.pytorch.org/docs/2.13/notes/randomness.html#reproducibility

## Running tensors and Pytorch objects on the GPUs (and making faster computations)

### 1. Getting a GPU

In [101]:
!nvidia-smi

Thu Jul 23 17:21:02 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 591.86                 Driver Version: 591.86         CUDA Version: 13.1     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3060 ...  WDDM  |   00000000:01:00.0  On |                  N/A |
| N/A   64C    P8             14W /  100W |     699MiB /   6144MiB |      7%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

### 2. Check for GPU access with Pytorch


In [103]:
# Check for GPU access with Pytorch
import torch
torch.cuda.is_available()

True

For Pytorch since it's capable of running compute on the GPU or CPU, it's best practise to setup device agnostic code:https://docs.pytorch.org/docs/2.13/notes/cuda.html#cuda-semantics

E.g. run on GPU if aviailable,wlse default to CPU

In [104]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [105]:
# Count number of devices
torch.cuda.device_count()

1

## 3. Putting tensors (and models) on the GPU

In [109]:
# Create a tensor (default on the GPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [110]:
# Move tensor to GPU(if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

In [111]:
# If tensor is on GPU, can't transform it ro Numpy
tensor_on_gpu.numpy()


TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [112]:
# To fix the GPU tensor with Numpy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3], dtype=int64)

In [113]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')